/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as PersonalTrainerRouteImport } from './routes/personal-trainer'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiBuilderRouteImport } from './routes/ai-builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as WorkoutsDayRouteImport } from './routes/workouts.$day'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalTrainerRoute = PersonalTrainerRouteImport.update({
  id: '/personal-trainer',
  path: '/personal-trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBuilderRoute = AiBuilderRouteImport.update({
  id: '/ai-builder',
  path: '/ai-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsDayRoute = WorkoutsDayRouteImport.update({
  id: '/workouts/$day',
  path: '/workouts/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-builder': typeof AiBuilderRoute
  '/dashboard': typeof DashboardRoute
  '/exercises': typeof ExercisesRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/onboarding': typeof OnboardingRoute
  '/personal-trainer': typeof PersonalTrainerRoute
  '/photos': typeof PhotosRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/workouts/$day': typeof WorkoutsDayRoute
  '/workouts/': typeof WorkoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-builder': typeof AiBuilderRoute
  '/dashboard': typeof DashboardRoute
  '/exercises': typeof ExercisesRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/onboarding': typeof OnboardingRoute
  '/personal-trainer': typeof PersonalTrainerRoute
  '/photos': typeof PhotosRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/workouts/$day': typeof WorkoutsDayRoute
  '/workouts': typeof WorkoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-builder': typeof AiBuilderRoute
  '/dashboard': typeof DashboardRoute
  '/exercises': typeof ExercisesRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/onboarding': typeof OnboardingRoute
  '/personal-trainer': typeof PersonalTrainerRoute
  '/photos': typeof PhotosRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/workouts/$day': typeof WorkoutsDayRoute
  '/workouts/': typeof WorkoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-builder'
    | '/dashboard'
    | '/exercises'
    | '/login'
    | '/measurements'
    | '/onboarding'
    | '/personal-trainer'
    | '/photos'
    | '/progress'
    | '/settings'
    | '/workouts/$day'
    | '/workouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-builder'
    | '/dashboard'
    | '/exercises'
    | '/login'
    | '/measurements'
    | '/onboarding'
    | '/personal-trainer'
    | '/photos'
    | '/progress'
    | '/settings'
    | '/workouts/$day'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/ai-builder'
    | '/dashboard'
    | '/exercises'
    | '/login'
    | '/measurements'
    | '/onboarding'
    | '/personal-trainer'
    | '/photos'
    | '/progress'
    | '/settings'
    | '/workouts/$day'
    | '/workouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiBuilderRoute: typeof AiBuilderRoute
  DashboardRoute: typeof DashboardRoute
  ExercisesRoute: typeof ExercisesRoute
  LoginRoute: typeof LoginRoute
  MeasurementsRoute: typeof MeasurementsRoute
  OnboardingRoute: typeof OnboardingRoute
  PersonalTrainerRoute: typeof PersonalTrainerRoute
  PhotosRoute: typeof PhotosRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  WorkoutsDayRoute: typeof WorkoutsDayRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-trainer': {
      id: '/personal-trainer'
      path: '/personal-trainer'
      fullPath: '/personal-trainer'
      preLoaderRoute: typeof PersonalTrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-builder': {
      id: '/ai-builder'
      path: '/ai-builder'
      fullPath: '/ai-builder'
      preLoaderRoute: typeof AiBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$day': {
      id: '/workouts/$day'
      path: '/workouts/$day'
      fullPath: '/workouts/$day'
      preLoaderRoute: typeof WorkoutsDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiBuilderRoute: AiBuilderRoute,
  DashboardRoute: DashboardRoute,
  ExercisesRoute: ExercisesRoute,
  LoginRoute: LoginRoute,
  MeasurementsRoute: MeasurementsRoute,
  OnboardingRoute: OnboardingRoute,
  PersonalTrainerRoute: PersonalTrainerRoute,
  PhotosRoute: PhotosRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  WorkoutsDayRoute: WorkoutsDayRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
